***Capstone Guideline : Named Entity Recognition Service***

Checkpoints : 
1. Instalasi : 1 poin
2. Membuat dan menggunakan model entity recognition : 2 poin
4. Membuat api untuk aplikasi entity recognition dengan tampilan web : 2 poin
5. Membuat api untuk aplikasi entity recognition tanpa tampilan web : 9 poin
6. Melakukan deployment aplikasi pada remote host : 2 poin

# Instalasi

Untuk membuat flask named entity recognition, kita dapat menggunakan libary : 
- flask : untuk membuat aplikasi / microservice (install : `pip install flask`)
- pandas : tools data analysis, digunakan selama pembuatan fitur aplikasi  (install : `pip install pandas`)
- spacy : model bahasa (install : `pip install spacy`)
- en_core_web_md : kamus bahasa yang akan digunakan spacy (install : `python -m spacy download en_core_web_md` atau `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.0.0/en_core_web_md-3.0.0.tar.gz`)

- requests : tools untuk mengirim dan menerima paket, digunakan untuk menguji aplikasi yang sudah dibuat (built-in python)

In [1]:
from flask import Flask,render_template,url_for,request
import pandas as pd
import spacy
from spacy import displacy
import en_core_web_md
import requests

# Membuat dan Menggunakan Model NER

Sebelum memodelkan bahasa /teks, hal pertama yang dibutuhkan adalah membuat model tersebut. Spacy memudahkan kita dengan memberikan model yang sudah dibuat. 

Jalankan sintaks berikut untuk meload model bahasa tersebut

In [2]:
# load model bahasa spacy
nlp = en_core_web_md.load()

Setelah memiliki model, komponen penting berikutnya dalah data yang akan dimodelkan. Dalam hal ini, kami memberi contoh sample buku Sherlock Holmes dan teks random sebagai data yang akan dimodelkan.

In [200]:
# load teks sherlock holmes
# f = open('sherlock_holmes.txt', 'r')
# sherlock_holmes = f.read().replace('\n', ' ')
# f.close()

# jika tidak ingin teks yang panjang, bisa gunakan contoh teks sendiri 
text = """This text is an example used for Algoritma's Capstone API Project. 
You can use any named entitiy such person name like Nicola Tesla, Steve Jobs, or even Elon Musk. 
Please mind that the model is trained on formal writing, thus slang will less likely to be recognized correctly."""

In [201]:
print(text)

This text is an example used for Algoritma's Capstone API Project.
You can use any named entitiy such person name like Nicola Tesla, Steve Jobs, or even Elon Musk.
Please mind that the model is trained on formal writing, thus slang will less likely to be recognized correctly.

In [3]:
# load teks sherlock holmes
f = open('sherlock_holmes.txt', 'r',encoding='utf-8')
sherlock_holmes = f.read().replace('\n', ' ')
f.close()

In [4]:
print(sherlock_holmes[:500])

A Study In Scarlet PART I.  (Being a reprint from the reminiscences of John H. Watson, M.D., late of the Army Medical Department.) Chapter I. Mr. Sherlock Holmes  In the year 1878 I took my degree of Doctor of Medicine of the University of London, and proceeded to Netley to go through the course prescribed for surgeons in the army. Having completed my studies there, I was duly attached to the Fifth Northumberland Fusiliers as Assistant Surgeon. The regiment was stationed in India at the time, an

Untuk menggunakan model Entity Recognition milik spacy, cukup masukkan teks sebagai parameter dalam membuat object bahasa seperti contoh berikut:

In [204]:
doc = nlp(text)

In [205]:
doc

This text is an example used for Algoritma's Capstone API Project.
You can use any named entitiy such person name like Nicola Tesla, Steve Jobs, or even Elon Musk.
Please mind that the model is trained on formal writing, thus slang will less likely to be recognized correctly.

In [5]:
doc2 = nlp(sherlock_holmes)

Untuk menampilkan nilai dari teks tersebut, panggil objek `doc` kembali

In [6]:
doc2[:100]

A Study In Scarlet PART I.  (Being a reprint from the reminiscences of John H. Watson, M.D., late of the Army Medical Department.) Chapter I. Mr. Sherlock Holmes  In the year 1878 I took my degree of Doctor of Medicine of the University of London, and proceeded to Netley to go through the course prescribed for surgeons in the army. Having completed my studies there, I was duly attached to the Fifth Northumberland Fusiliers as Assistant Surgeon. The regiment was stationed in India at the time, and before

In [208]:
#MELIHAT ENTITAS YG DIDAPATKAN
doc.ents

(Algoritma, Capstone API Project, Nicola Tesla, Steve Jobs)

In [6]:
doc2.ents[:20]

(John H. Watson,
 M.D.,
 the Army Medical Department,
 Chapter I.,
 Sherlock Holmes  ,
 the year 1878,
 the University of London,
 Netley,
 Fifth,
 India,
 second,
 Afghan,
 Bombay,
 Berkshires,
 Maiwand,
 Jezail,
 Ghazis,
 Murray,
 British,
 Peshawar)

In [210]:
#MELIHAT ENTITAS VALUE PADA BARIS KE-1
doc.ents[0].text

'Algoritma'

In [211]:
#MELIHAT KATEGORI ENTITTAS PADA BARIS KE-1
doc.ents[0].label_

'ORG'

In [7]:
doc2.ents[0].text

'John H. Watson'

In [8]:
doc2.ents[0].label_

'PERSON'

Untuk mengakes seluruh element entitas , jalankan sintaks berikut :

In [214]:
# membuat pasangan label dan nilai entitas
d = [(ent.label_, ent.text) for ent in doc.ents]

# transform pasangan label menjadi dataframe 
df = pd.DataFrame(d, columns=['category', 'value'])

In [215]:
df

  category                 value
0      ORG             Algoritma
1      ORG  Capstone API Project
2   PERSON          Nicola Tesla
3   PERSON            Steve Jobs

In [9]:
d2 = [(ent.label_, ent.text) for ent in doc2.ents]
df2 = pd.DataFrame(d2, columns=['category', 'value'])
df2

      category                        value
0       PERSON               John H. Watson
1          GPE                         M.D.
2          ORG  the Army Medical Department
3          LAW                   Chapter I.
4       PERSON            Sherlock Holmes
...        ...                          ...
2375    PERSON                    Forrester
2376  CARDINAL                   two-thirds
2377  CARDINAL                          one
2378    PERSON                      Morstan
2379       GPE                         Agra

[2380 rows x 2 columns]

In [15]:
df2["category"].unique()

array(['PERSON', 'GPE', 'ORG', 'LAW', 'DATE', 'ORDINAL', 'NORP',
       'CARDINAL', 'FAC', 'TIME', 'WORK_OF_ART', 'PRODUCT', 'LOC',
       'QUANTITY', 'EVENT', 'LANGUAGE', 'MONEY'], dtype=object)

In [17]:
df2[df2["category"]=="ORDINAL"]

     category   value
8     ORDINAL   Fifth
10    ORDINAL  second
41    ORDINAL  second
42    ORDINAL   first
47    ORDINAL   first
...       ...     ...
2203  ORDINAL   first
2237  ORDINAL  second
2294  ORDINAL   first
2352  ORDINAL   first
2372  ORDINAL   first

[89 rows x 2 columns]

# Membuat API NER dengan tampilan Web

## app.py

Untuk membuat aplikasi NER dengan flask, silakan **lengkapi code berikut** dan salin kedalam file `app.py`.

In [44]:
from flask import Flask,render_template,url_for,request, jsonify
import re
import pandas as pd
import spacy
from spacy import displacy
import en_core_web_md
import json 

# @TASK : Load model bahasa 
nlp = en_core_web_md.load()
# END OF TASK 

app = Flask(__name__)

@app.route('/')
def index():
    return render_template("index.html")

@app.route('/process',methods=["POST"])
def process():
    if request.method == 'POST':
        choice = request.form['taskoption']
        rawtext = request.form['rawtext']
        doc2 = nlp(rawtext)
        d2 = []
        if len(doc2.ents) > 0:
            for ent in doc2.ents:
                d2.append((ent.label_, ent.text))
                df2 = pd.DataFrame(d2, columns=['category', 'value'])

                # @TASK : COMPLETE THE FOLLOWING CODES
                ORG_named_entity = df2[df2["category"] == "ORG"]["value"] # Subset semua entitas dengan kategori 'ORG'
                PERSON_named_entity = df2[df2["category"] == "PERSON"]["value"] # Subset semua entitas dengan kategori 'PERSON'
                GPE_named_entity = df2[df2["category"] == "GPE"]["value"] # Subset semua entitas dengan kategori 'GPE'
                MONEY_named_entity = df2[df2["category"] == "MONEY"]["value"] # Subset semua entitas dengan kategori 'MONEY'
                NORP_named_entity = df2[df2["category"] == "NORP"]["value"]
                FAC_named_entity = df2[df2["category"] == "FAC"]["value"]
                LOC_named_entity = df2[df2["category"] == "LOC"]["value"]
                PRODUCT_named_entity = df2[df2["category"] == "PRODUCT"]["value"]
                EVENT_named_entity = df2[df2["category"] == "EVENT"]["value"]
                WORK_OF_ART_named_entity = df2[df2["category"] == "WORK_OF_ART"]["value"]
                LAW_named_entity = df2[df2["category"] == "LAW"]["value"]
                LANGUAGE_named_entity = df2[df2["category"] == "LANGUAGE"]["value"]
                DATE_named_entity = df2[df2["category"] == "DATE"]["value"]
                TIME_named_entity = df2[df2["category"] == "TIME"]["value"]
                QUANTITY_named_entity = df2[df2["category"] == "QUANTITY"]["value"]
                ORDINAL_named_entity = df2[df2["category"] == "ORDINAL"]["value"]
                CARDINAL_named_entity = df2[df2["category"] == "CARDINAL"]["value"]
                # END OF TASK 

            if choice == 'organization':
                results = ORG_named_entity
                num_of_results = len(results)
            elif choice == 'person':
                results = PERSON_named_entity
                num_of_results = len(results)
            elif choice == 'geopolitical':
                results = GPE_named_entity
                num_of_results = len(results)
            elif choice == 'money':
                results = MONEY_named_entity
                num_of_results = len(results)
            elif choice == 'norp':
                results = NORP_named_entity
                num_of_results = len(results)
            elif choice == 'fac':
                results = FAC_named_entity
                num_of_results = len(results)
            elif choice == 'loc':
                results = LOC_named_entity
                num_of_results = len(results)
            elif choice == 'product':
                results = PRODUCT_named_entity
                num_of_results = len(results)
            elif choice == 'event':
                results = EVENT_named_entity
                num_of_results = len(results)
            elif choice == 'work_of_art':
                results = WORK_OF_ART_named_entity
                num_of_results = len(results)
            elif choice == 'law':
                results = LAW_named_entity
                num_of_results = len(results)
            elif choice == 'language':
                results = LANGUAGE_named_entity
                num_of_results = len(results)
            elif choice == 'date':
                results = DATE_named_entity
                num_of_results = len(results)
            elif choice == 'time':
                results = TIME_named_entity
                num_of_results = len(results)
            elif choice == 'quantity':
                results = QUANTITY_named_entity
                num_of_results = len(results)
            elif choice == 'ordinal':
                results = ORDINAL_named_entity
                num_of_results = len(results)
            elif choice == 'cardinal':
                results = CARDINAL_named_entity
                num_of_results = len(results)
        else:
            results = pd.DataFrame()
            num_of_results = len(results)

    return render_template("index.html",results=results,num_of_results = num_of_results, original_text = rawtext)


if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

 * Restarting with windowsapi reloader

SystemExit: 1

C:\Users\asus\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3426: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

## menjalankan app.py

Untuk menjalankan app.py, silakan buka terminal/console/anaconda prompt menuju direktori tempat app.py berada, lalu jalnkan sintaks 
`python app.py` .

Jika code berjalan dengan baik, silakan buka laman yang dirujuk pada console (biasanya http://127.0.0.1:5000/) melalui browser dan aplikasi akan berjalan sesuai tampilan berikut : 

![](assets/default_homepage.png)
![](Capture.jpg)

Setelah aplikasi berjalan, silakan inputkan teks dan pilih kategori yang akan diekstrak, lalu pilih submit. Jika tidak ada eror, maka form result akan memberikan hasil kembalian berupa banyaknya entitas yang dikenali dan list entitas tersebut.

# Membuat API NER tanpa tampilan WEB

## Membuat Endpoint

Dalam web service, endpoint adalah sebuah alamat spesifik yang ditujukan untuk kebutuhan khusus. 
Sebagai contoh, berikut adalah beberapa endpoint web API milik spotify : 
- https://api.spotify.com/v1/albums{id} : Digunakan untuk mengakses album dengan album id = id
- https://api.spotify.com/v1/artists/{id} : digunakan untuk mengakses artist dengan artist id = id
- https://api.spotify.com/v1/tracks/{id} : digunakan untuk mengakses tracks dengan track id = id

Dalam flask, endpoint dinotasikan dengan `@app.route('alamat endpoint')`, diikuti dengan fungsi yang akan dijalankan. 
Sebelumnya, dalam `app.py`, kita sudah membuat sebuah endpoint home ('/') dengan sintaks : 
```python
@app.route('/')
def index():
    return render_template("index.html")
```    

Menggunakan sintaks diatas, ketika user mengakses aplikasi kita di menu utama, maka fungsi `index()` akan dijalankan. 

Sebagai contoh tambahan, coba salin sintaks berikut kedalam `app.py` dan coba akses endpoint tersebut 

```python
@app.route('/endpoint_tertentu')
def nama_fungsi_tertentu():
    # secara teknis, kita dapat melakukan apapun dalam fungsi ini 
    return ("Fungsi ini akan dijalankan saat endpoint tersebut diakses")
```


**notes**: nama fungsi dalam aplikasi flask harus unik.

## Endpoint Methods

Senada dengan konsep CRUD (Create, Read, Update, Delete) dalam database, dalam API konsep tersebut diadopsi menjadi :
- POST(CREATE),
- GET(READ),
- PUT(UPDATE),
- DELETE

Secara konsep, method POST, GET, PUT, dan DELETE dibuat untuk mengatur API agar dapat lebih terstruktur. Meskipun pada prakterknya, endpoint yang kita definisikan menggunakan method "POST" tidaklah harus untuk membuat data. Artinya, tidak ada aturan yang mengharuskan kita untuk menuliskan jenis method dalam setiap endpoints kita (default endpoints menggunakan method GET).

Dalam capstone ini, kita hanya akan berfokus pada 2 jenis method, GET dan POST. Sebagai contoh tambahan, silakan salin sintaks enspoint berikut kedalma `app.py`, lalu jalankan ulang aplikasinya dan lihat perbedaan saat melakukan akses terhadap kedua endpoint tersebut. 

```python
@app.route('/endpoint_get', methods=['GET'])
def contoh_get():
    return ("Contoh endpoint get")
    
@app.route('/endpoint_post', methods=['POST'])
def contoh_post():
    return ("Contoh endpoint post")
    
@app.route('/endpoint_multi', methods=['GET', 'POST'])
def multi_method():
    if request.method == 'POST':
        return ("Nilai ini akan dikembalikan jika endpoint ini diakses dengan method POST")
    else : 
        return ("Nilai ini akan dikembalikan jika endpoint ini diakses dengan method GET")
```

**Note : Secara default, mengakses endpoint melaui browser akan menggunakan method 'GET'**. 

Untuk mempermudah pengujian, disarankan untuk menggunakan tools lain seperti "postman", atau menggunakan python.

## Mengakses endpoint menggunakan python

Dalam banyak kasus, web API tidak dipanggil melalui browser, melainkan pada level aplikasi / code. Untuk mengakses web api menggunakan python, gunakan `curl` atau `requests`. Code berikut akan mengakses endpoint yang sama dengan method yang berbeda:

In [11]:
import requests
response_post = requests.request(method='POST', url='http://localhost:5000/endpoint_multi')
response_get = requests.request(method='GET', url='http://localhost:5000/endpoint_multi')

Respon dari sebuah service web API dibungkus dalam http response. Jika objek `response_post` dipanggil, maka yang tampil adalah nilai kode status repons tersebut (silakan merujuk referensi HTTP response code untuk informasi lebih lengkap) :

In [12]:
response_post

In [31]:
# secara eksplisit mengambil atribut status code dari objek response
response_post.status_code

200

Untuk dapat mengambil konten dari nilai yang diterima, akses atribut .text atau .json jika nilai yang diterima berupa json

In [14]:
response_post.text

'Nilai ini akan dikembalikan jika endpoint ini diakses dengan method POST'

In [15]:
response_get.text

'Nilai ini akan dikembalikan jika endpoint ini diakses dengan method GET'

Referensi : [HTTP response code, by mozilla](https://developer.mozilla.org/id/docs/Web/HTTP/Status)

## Mengirim data ke endpoint

Untuk melakukan ekstraksi entitas terhadap data yang kita miliki pada layanan web api, kita harus mengirimkan data tersebut melalui protokol http. 
Method API yang biasa digunakan dalam melayani request tersebut adalah POST. 
Agar data dapat dikirim dengan baik, data harus dikirim dalam bentuk objek JSON (JSON dalam python = Dictionary). 


Sebagai contoh, sintaks berikut akan mengirimkan data json kedalam endpoint yang dituju.

In [16]:
# membuat data yang akan dikirim (dalam bentuk dictionary)
data_yang_akan_dikirim = {
    'nama' : 'Steve', 
    'usia' : 12, 
    'pekerjaan' : 'Data Scientist'
}

# endpoint yang akan dituju
endpoint = 'http://localhost:5000/tes_send_json'

# mengeksekusi request
response = requests.request(method='POST', url=endpoint, json=data_yang_akan_dikirim)

In [17]:
#404 Karena endpoint "/tes_send_json" belum dibuat
response

Jika dijalankan, sintaks diatas tentu akan menghasilkan error. Hal ini dikarenakan pada aplikasi kita belum terdapat endpoint `'/send_json'`. 
Ikuti langkah berikutnya untuk membuat endpoint yang dapat menerima objek yang kita kirim tersebut

## Membuat endpoint yang menerima data

Untuk membaca data yang dikirimkan pada endpoint tertentu, kita dapat menggunakan method method `request.get_json()` dari flask. (Silakan merujuk ke app.py dan pastikan terdapat sintaks `from flask import request`. 

Silakan tambahkan endpoint dibawah ini pada `app.py` dan jalankan kembali request pada segmen sebelumnya

```python
@app.route('/tes_send_json', methods=['POST'])
def tes_send_json():
    data = request.get_json() # proses membaca json yang dikirim 
    nama = data['nama']
    usia = data['usia']
    pekerjaan = data['pekerjaan']
    
    return ("Halo, {nama}. Usiamu adalah {usia} dan pekerjaanmu adalah {pekerjaan}".format(nama=nama, usia=usia, pekerjaan=pekerjaan))
```

In [33]:
# coba jalankan request di segment sebelumnya

data_yang_akan_dikirim = {
    'nama' : 'Steve', 
    'usia' : 12, 
    'pekerjaan' : 'Data Scientist'
}

endpoint = 'http://localhost:5000/tes_send_json'

response = requests.request(method='POST', url=endpoint, json=data_yang_akan_dikirim)

In [34]:
# response berhasil, karena endpoint sudah dibuat
response

In [35]:
# isi dari reponse yg brupa string
response.text

'Halo, Steve. Usiamu adalah 12 dan pekerjaanmu adalah Data Scientist'

## Mengembalikan hasil pemrosesan sebagai objek JSON dari endpoint

Dalam beberapa kasus, analisis atau pengelolaan yang kita lakukan berakhir pada tipe data DataFrame milik pandas. Untuk mengubah DataFrame menjadi json, gunakan method `.to_json()`. Berikut adalah contoh endpoint yang mengembalikan dataframe dalam bentuk json.

```python
@app.route('/tes_return_json', methods=['POST'])
def tes_return_json():
    data = request.get_json() # proses membaca json yang dikirim 
    df = pd.DataFrame([data]) # mengolah data menjadi dataframe

    return (df.to_json()) # mengembalikan dataframe dalam bentuk json
```

In [36]:
data_yang_akan_dikirim = {
    'nama' : 'Steve', 
    'usia' : 12, 
    'pekerjaan' : 'Data Scientist'
}

endpoint = 'http://localhost:5000/tes_return_json'

response = requests.request(method='POST', url=endpoint, json=data_yang_akan_dikirim)

In [37]:
response

In [38]:
response.text

'{"nama":{"0":"Steve"},"usia":{"0":12},"pekerjaan":{"0":"Data Scientist"}}'

In [40]:
response.json()

{'nama': {'0': 'Steve'},
 'usia': {'0': 12},
 'pekerjaan': {'0': 'Data Scientist'}}

In [41]:
pd.DataFrame(response.json())

    nama  usia       pekerjaan
0  Steve    12  Data Scientist

## Task : Endpoint

Sebagai tugas dalam capstone ini, buatlah endpoint yang dapat mengembalikan **semua** jenis entitas dari teks yang dikirim. 

Berikut adalah spesifikasi singkat dari endpoint tersebut
- Input : Teks dalam bentuk JSON, dengan raw teks disimpan dalam elemen "text" seperti contoh berikut: 
```python
{
    "text" : "ini adalah contoh teks yang dikirim"
}
```
- Output : Bentuk JSON dari dataframe yang berisi 2 kolom (kategori entitas, value). 

Untuk menyelesaikan task tersebut silakan lengkapi code endpoint berikut lalu tambahkan pada `app.py`

In [45]:
@app.route('/get_entities', methods=['POST'])
def get_entities():
    
    # ambil data dari json yang diterima endpoint
    data3 = request.get_json()
    
    # ambil nilai teks dari data
    text3 = data3['text3']
    
    # modelkan teks dengan model spacy 
    doc3 = nlp(text3)
    
    # membuat pasangan label dan nilai entitas
    d3 = [(ent.label_, ent.text) for ent in doc3.ents]

    # transform pasangan label menjadi dataframe 
    df3 = pd.DataFrame(d3, columns=['category', 'value'])
    
    return (df3.to_json())

In [46]:
# Jalankan sintaks berikut untuk menguji endpoint tersebut

text3 = sherlock_holmes
data3 = {"text3": text3}
url = 'http://localhost:5000/get_entities'
response3 = requests.request(method='POST', url=url, json=data3)
response3.json()

{'category': {'0': 'PERSON',
  '1': 'GPE',
  '2': 'ORG',
  '3': 'LAW',
  '4': 'PERSON',
  '5': 'DATE',
  '6': 'ORG',
  '7': 'GPE',
  '8': 'ORDINAL',
  '9': 'GPE',
  '10': 'ORDINAL',
  '11': 'NORP',
  '12': 'GPE',
  '13': 'GPE',
  '14': 'GPE',
  '15': 'GPE',
  '16': 'ORG',
  '17': 'PERSON',
  '18': 'NORP',
  '19': 'GPE',
  '20': 'NORP',
  '21': 'DATE',
  '22': 'GPE',
  '23': 'NORP',
  '24': 'DATE',
  '25': 'GPE',
  '26': 'DATE',
  '27': 'GPE',
  '28': 'CARDINAL',
  '29': 'GPE',
  '30': 'GPE',
  '31': 'ORG',
  '32': 'DATE',
  '33': 'FAC',
  '34': 'GPE',
  '35': 'PERSON',
  '36': 'GPE',
  '37': 'GPE',
  '38': 'GPE',
  '39': 'PERSON',
  '40': 'GPE',
  '41': 'ORDINAL',
  '42': 'ORDINAL',
  '43': 'TIME',
  '44': 'GPE',
  '45': 'PERSON',
  '46': 'ORG',
  '47': 'ORDINAL',
  '48': 'GPE',
  '49': 'DATE',
  '50': 'TIME',
  '51': 'GPE',
  '52': 'GPE',
  '53': 'GPE',
  '54': 'PERSON',
  '55': 'PERSON',
  '56': 'PERSON',
  '57': 'GPE',
  '58': 'GPE',
  '59': 'DATE',
  '60': 'CARDINAL',
  '61': 'GPE',
  '62': 'TIME',
  '63': 'CARDINAL',
  '64': 'CARDINAL',
  '65': 'DATE',
  '66': 'PERSON',
  '67': 'GPE',
  '68': 'DATE',
  '69': 'ORG',
  '70': 'ORG',
  '71': 'PERSON',
  '72': 'GPE',
  '73': 'PERSON',
  '74': 'GPE',
  '75': 'GPE',
  '76': 'PERSON',
  '77': 'GPE',
  '78': 'CARDINAL',
  '79': 'FAC',
  '80': 'DATE',
  '81': 'CARDINAL',
  '82': 'TIME',
  '83': 'TIME',
  '84': 'DATE',
  '85': 'TIME',
  '86': 'GPE',
  '87': 'GPE',
  '88': 'GPE',
  '89': 'LAW',
  '90': 'WORK_OF_ART',
  '91': 'DATE',
  '92': 'CARDINAL',
  '93': 'PERSON',
  '94': 'CARDINAL',
  '95': 'PERSON',
  '96': 'DATE',
  '97': 'CARDINAL',
  '98': 'TIME',
  '99': 'DATE',
  '100': 'TIME',
  '101': 'DATE',
  '102': 'GPE',
  '103': 'PERSON',
  '104': 'LAW',
  '105': 'DATE',
  '106': 'GPE',
  '107': 'DATE',
  '108': 'NORP',
  '109': 'PERSON',
  '110': 'PERSON',
  '111': 'TIME',
  '112': 'DATE',
  '113': 'PERSON',
  '114': 'CARDINAL',
  '115': 'CARDINAL',
  '116': 'DATE',
  '117': 'TIME',
  '118': 'TIME',
  '119': 'PERSON',
  '120': 'ORDINAL',
  '121': 'PERSON',
  '122': 'CARDINAL',
  '123': 'WORK_OF_ART',
  '124': 'PRODUCT',
  '125': 'CARDINAL',
  '126': 'ORG',
  '127': 'LOC',
  '128': 'GPE',
  '129': 'CARDINAL',
  '130': 'ORG',
  '131': 'PERSON',
  '132': 'ORDINAL',
  '133': 'LOC',
  '134': 'CARDINAL',
  '135': 'PERSON',
  '136': 'GPE',
  '137': 'CARDINAL',
  '138': 'DATE',
  '139': 'PERSON',
  '140': 'ORDINAL',
  '141': 'ORDINAL',
  '142': 'GPE',
  '143': 'GPE',
  '144': 'NORP',
  '145': 'GPE',
  '146': 'ORDINAL',
  '147': 'GPE',
  '148': 'PERSON',
  '149': 'PERSON',
  '150': 'PERSON',
  '151': 'PERSON',
  '152': 'CARDINAL',
  '153': 'PERSON',
  '154': 'PERSON',
  '155': 'PERSON',
  '156': 'PERSON',
  '157': 'TIME',
  '158': 'PERSON',
  '159': 'DATE',
  '160': 'CARDINAL',
  '161': 'DATE',
  '162': 'ORG',
  '163': 'ORG',
  '164': 'PERSON',
  '165': 'PERSON',
  '166': 'ORG',
  '167': 'ORG',
  '168': 'LAW',
  '169': 'ORG',
  '170': 'ORG',
  '171': 'CARDINAL',
  '172': 'CARDINAL',
  '173': 'CARDINAL',
  '174': 'PERSON',
  '175': 'PERSON',
  '176': 'TIME',
  '177': 'CARDINAL',
  '178': 'LOC',
  '179': 'FAC',
  '180': 'CARDINAL',
  '181': 'PERSON',
  '182': 'GPE',
  '183': 'GPE',
  '184': 'CARDINAL',
  '185': 'PERSON',
  '186': 'PERSON',
  '187': 'GPE',
  '188': 'PERSON',
  '189': 'ORG',
  '190': 'ORG',
  '191': 'ORDINAL',
  '192': 'TIME',
  '193': 'FAC',
  '194': 'TIME',
  '195': 'PERSON',
  '196': 'PERSON',
  '197': 'PERSON',
  '198': 'FAC',
  '199': 'QUANTITY',
  '200': 'FAC',
  '201': 'CARDINAL',
  '202': 'CARDINAL',
  '203': 'CARDINAL',
  '204': 'CARDINAL',
  '205': 'CARDINAL',
  '206': 'TIME',
  '207': 'QUANTITY',
  '208': 'PERSON',
  '209': 'PERSON',
  '210': 'PERSON',
  '211': 'CARDINAL',
  '212': 'PERSON',
  '213': 'ORDINAL',
  '214': 'PERSON',
  '215': 'PERSON',
  '216': 'PERSON',
  '217': 'ORG',
  '218': 'CARDINAL',
  '219': 'CARDINAL',
  '220': 'DATE',
  '221': 'PERSON',
  '222': 'CARDINAL',
  '223': 'DATE',
  '224': 'GPE',
  '225': 'PERSON',
  '226': 'ORG',
  '227': 'PERSON',
  '228': 'ORDINAL',
  '229': 'PERSON',
  '230': 'GPE',
  '231': 'DATE',
  '232': 'PERSON',
  '233': 'ORG',
  '234': 'CARDINAL',
  '235': 'PERSON',
  '236': 'ORG',
  '237': 'PERSON',
  '238': 'PERSON',
  '239': 'CARDINAL',
  '240': 'GPE',
  '241': 'GPE',
  '242': 'PERSON',
  '243': 'NORP',
  '244': 'PERSON',
  '245': 'GPE',
  '246': 'PERSON',
  '247': 'QUANTITY',
  '248': 'PERSON',
  '249': 'PERSON',
  '250': 'CARDINAL',
  '251': 'PERSON',
  '252': 'CARDINAL',
  '253': 'PERSON',
  '254': 'ORG',
  '255': 'ORG',
  '256': 'GPE',
  '257': 'GPE',
  '258': 'PERSON',
  '259': 'ORG',
  '260': 'CARDINAL',
  '261': 'ORG',
  '262': 'GPE',
  '263': 'TIME',
  '264': 'PERSON',
  '265': 'ORG',
  '266': 'PERSON',
  '267': 'PERSON',
  '268': 'PERSON',
  '269': 'PERSON',
  '270': 'PERSON',
  '271': 'PERSON',
  '272': 'ORDINAL',
  '273': 'TIME',
  '274': 'CARDINAL',
  '275': 'TIME',
  '276': 'CARDINAL',
  '277': 'ORG',
  '278': 'PERSON',
  '279': 'PERSON',
  '280': 'PERSON',
  '281': 'PERSON',
  '282': 'DATE',
  '283': 'ORG',
  '284': 'FAC',
  '285': 'CARDINAL',
  '286': 'QUANTITY',
  '287': 'ORG',
  '288': 'CARDINAL',
  '289': 'CARDINAL',
  '290': 'CARDINAL',
  '291': 'PERSON',
  '292': 'PERSON',
  '293': 'ORG',
  '294': 'PERSON',
  '295': 'CARDINAL',
  '296': 'PERSON',
  '297': 'NORP',
  '298': 'PERSON',
  '299': 'NORP',
  '300': 'CARDINAL',
  '301': 'LAW',
  '302': 'PERSON',
  '303': 'TIME',
  '304': 'CARDINAL',
  '305': 'FAC',
  '306': 'PERSON',
  '307': 'PERSON',
  '308': 'ORDINAL',
  '309': 'PERSON',
  '310': 'ORG',
  '311': 'ORDINAL',
  '312': 'CARDINAL',
  '313': 'TIME',
  '314': 'DATE',
  '315': 'TIME',
  '316': 'CARDINAL',
  '317': 'CARDINAL',
  '318': 'TIME',
  '319': 'PERSON',
  '320': 'TIME',
  '321': 'CARDINAL',
  '322': 'CARDINAL',
  '323': 'CARDINAL',
  '324': 'QUANTITY',
  '325': 'CARDINAL',
  '326': 'ORG',
  '327': 'ORG',
  '328': 'PERSON',
  '329': 'PERSON',
  '330': 'CARDINAL',
  '331': 'CARDINAL',
  '332': 'CARDINAL',
  '333': 'ORDINAL',
  '334': 'NORP',
  '335': 'PERSON',
  '336': 'PERSON',
  '337': 'NORP',
  '338': 'NORP',
  '339': 'NORP',
  '340': 'NORP',
  '341': 'CARDINAL',
  '342': 'PERSON',
  '343': 'PERSON',
  '344': 'TIME',
  '345': 'ORG',
  '346': 'CARDINAL',
  '347': 'TIME',
  '348': 'TIME',
  '349': 'EVENT',
  '350': 'TIME',
  '351': 'PERSON',
  '352': 'GPE',
  '353': 'FAC',
  '354': 'CARDINAL',
  '355': 'FAC',
  '356': 'CARDINAL',
  '357': 'CARDINAL',
  '358': 'CARDINAL',
  '359': 'LOC',
  '360': 'WORK_OF_ART',
  '361': 'PERSON',
  '362': 'CARDINAL',
  '363': 'PERSON',
  '364': 'PERSON',
  '365': 'PERSON',
  '366': 'CARDINAL',
  '367': 'ORG',
  '368': 'ORG',
  '369': 'PERSON',
  '370': 'PERSON',
  '371': 'PERSON',
  '372': 'PERSON',
  '373': 'CARDINAL',
  '374': 'TIME',
  '375': 'PERSON',
  '376': 'ORDINAL',
  '377': 'CARDINAL',
  '378': 'PERSON',
  '379': 'ORG',
  '380': 'PERSON',
  '381': 'PERSON',
  '382': 'TIME',
  '383': 'PERSON',
  '384': 'GPE',
  '385': 'PERSON',
  '386': 'PERSON',
  '387': 'DATE',
  '388': 'NORP',
  '389': 'ORG',
  '390': 'TIME',
  '391': 'TIME',
  '392': 'ORDINAL',
  '393': 'FAC',
  '394': 'TIME',
  '395': 'ORG',
  '396': 'GPE',
  '397': 'PERSON',
  '398': 'DATE',
  '399': 'PERSON',
  '400': 'CARDINAL',
  '401': 'PERSON',
  '402': 'TIME',
  '403': 'PERSON',
  '404': 'NORP',
  '405': 'TIME',
  '406': 'TIME',
  '407': 'DATE',
  '408': 'ORG',
  '409': 'LANGUAGE',
  '410': 'LOC',
  '411': 'DATE',
  '412': 'PERSON',
  '413': 'PERSON',
  '414': 'PERSON',
  '415': 'DATE',
  '416': 'PERSON',
  '417': 'PERSON',
  '418': 'TIME',
  '419': 'FAC',
  '420': 'PERSON',
  '421': 'TIME',
  '422': 'PERSON',
  '423': 'TIME',
  '424': 'CARDINAL',
  '425': 'PERSON',
  '426': 'WORK_OF_ART',
  '427': 'PERSON',
  '428': 'PERSON',
  '429': 'CARDINAL',
  '430': 'PERSON',
  '431': 'GPE',
  '432': 'PERSON',
  '433': 'PERSON',
  '434': 'PERSON',
  '435': 'PERSON',
  '436': 'PERSON',
  '437': 'TIME',
  '438': 'PERSON',
  '439': 'PERSON',
  '440': 'TIME',
  '441': 'DATE',
  '442': 'GPE',
  '443': 'PERSON',
  '444': 'CARDINAL',
  '445': 'PERSON',
  '446': 'CARDINAL',
  '447': 'GPE',
  '448': 'PERSON',
  '449': 'PERSON',
  '450': 'PERSON',
  '451': 'PERSON',
  '452': 'LAW',
  '453': 'PERSON',
  '454': 'DATE',
  '455': 'ORG',
  '456': 'ORG',
  '457': 'NORP',
  '458': 'NORP',
  '459': 'GPE',
  '460': 'ORG',
  '461': 'ORG',
  '462': 'ORG',
  '463': 'NORP',
  '464': 'PERSON',
  '465': 'FAC',
  '466': 'ORG',
  '467': 'GPE',
  '468': 'NORP',
  '469': 'DATE',
  '470': 'PERSON',
  '471': 'ORG',
  '472': 'GPE',
  '473': 'PERSON',
  '474': 'CARDINAL',
  '475': 'DATE',
  '476': 'ORDINAL',
  '477': 'FAC',
  '478': 'GPE',
  '479': 'PERSON',
  '480': 'FAC',
  '481': 'GPE',
  '482': 'PERSON',
  '483': 'PERSON',
  '484': 'PERSON',
  '485': 'ORG',
  '486': 'ORG',
  '487': 'PERSON',
  '488': 'PERSON',
  '489': 'ORG',
  '490': 'PERSON',
  '491': 'PERSON',
  '492': 'ORG',
  '493': 'NORP',
  '494': 'PERSON',
  '495': 'CARDINAL',
  '496': 'PERSON',
  '497': 'PERSON',
  '498': 'CARDINAL',
  '499': 'CARDINAL',
  '500': 'CARDINAL',
  '501': 'PERSON',
  '502': 'GPE',
  '503': 'PERSON',
  '504': 'TIME',
  '505': 'CARDINAL',
  '506': 'PERSON',
  '507': 'PERSON',
  '508': 'ORG',
  '509': 'PERSON',
  '510': 'DATE',
  '511': 'CARDINAL',
  '512': 'PERSON',
  '513': 'PERSON',
  '514': 'PERSON',
  '515': 'PERSON',
  '516': 'PERSON',
  '517': 'PERSON',
  '518': 'ORDINAL',
  '519': 'NORP',
  '520': 'PERSON',
  '521': 'PERSON',
  '522': 'PERSON',
  '523': 'ORG',
  '524': 'CARDINAL',
  '525': 'FAC',
  '526': 'PERSON',
  '527': 'PERSON',
  '528': 'ORG',
  '529': 'PERSON',
  '530': 'ORG',
  '531': 'ORG',
  '532': 'PERSON',
  '533': 'PERSON',
  '534': 'PERSON',
  '535': 'PERSON',
  '536': 'GPE',
  '537': 'PERSON',
  '538': 'TIME',
  '539': 'PERSON',
  '540': 'CARDINAL',
  '541': 'CARDINAL',
  '542': 'CARDINAL',
  '543': 'CARDINAL',
  '544': 'CARDINAL',
  '545': 'ORDINAL',
  '546': 'TIME',
  '547': 'PERSON',
  '548': 'PERSON',
  '549': 'PERSON',
  '550': 'PERSON',
  '551': 'PERSON',
  '552': 'ORG',
  '553': 'PERSON',
  '554': 'DATE',
  '555': 'PERSON',
  '556': 'GPE',
  '557': 'PERSON',
  '558': 'TIME',
  '559': 'TIME',
  '560': 'PERSON',
  '561': 'CARDINAL',
  '562': 'PERSON',
  '563': 'DATE',
  '564': 'QUANTITY',
  '565': 'ORG',
  '566': 'TIME',
  '567': 'PERSON',
  '568': 'PERSON',
  '569': 'PERSON',
  '570': 'PERSON',
  '571': 'PERSON',
  '572': 'TIME',
  '573': 'PERSON',
  '574': 'PERSON',
  '575': 'PERSON',
  '576': 'PERSON',
  '577': 'CARDINAL',
  '578': 'TIME',
  '579': 'CARDINAL',
  '580': 'PERSON',
  '581': 'CARDINAL',
  '582': 'PERSON',
  '583': 'PERSON',
  '584': 'PERSON',
  '585': 'PERSON',
  '586': 'FAC',
  '587': 'PERSON',
  '588': 'PERSON',
  '589': 'PERSON',
  '590': 'PERSON',
  '591': 'PERSON',
  '592': 'PERSON',
  '593': 'PERSON',
  '594': 'PERSON',
  '595': 'PERSON',
  '596': 'PERSON',
  '597': 'PERSON',
  '598': 'PERSON',
  '599': 'PERSON',
  '600': 'PERSON',
  '601': 'ORG',
  '602': 'TIME',
  '603': 'LAW',
  '604': 'WORK_OF_ART',
  '605': 'PERSON',
  '606': 'CARDINAL',
  '607': 'PERSON',
  '608': 'PERSON',
  '609': 'PERSON',
  '610': 'PERSON',
  '611': 'PERSON',
  '612': 'PERSON',
  '613': 'ORDINAL',
  '614': 'PERSON',
  '615': 'PERSON',
  '616': 'PERSON',
  '617': 'PERSON',
  '618': 'PERSON',
  '619': 'CARDINAL',
  '620': 'FAC',
  '621': 'CARDINAL',
  '622': 'ORDINAL',
  '623': 'TIME',
  '624': 'PERSON',
  '625': 'FAC',
  '626': 'PERSON',
  '627': 'GPE',
  '628': 'NORP',
  '629': 'GPE',
  '630': 'PERSON',
  '631': 'TIME',
  '632': 'PERSON',
  '633': 'DATE',
  '634': 'TIME',
  '635': 'TIME',
  '636': 'TIME',
  '637': 'ORG',
  '638': 'ORG',
  '639': 'FAC',
  '640': 'PERSON',
  '641': 'DATE',
  '642': 'CARDINAL',
  '643': 'ORDINAL',
  '644': 'DATE',
  '645': 'PERSON',
  '646': 'PERSON',
  '647': 'PERSON',
  '648': 'PERSON',
  '649': 'PERSON',
  '650': 'ORDINAL',
  '651': 'PERSON',
  '652': 'PERSON',
  '653': 'PERSON',
  '654': 'QUANTITY',
  '655': 'GPE',
  '656': 'DATE',
  '657': 'LOC',
  '658': 'PERSON',
  '659': 'CARDINAL',
  '660': 'PERSON',
  '661': 'PERSON',
  '662': 'PERSON',
  '663': 'FAC',
  '664': 'PERSON',
  '665': 'PERSON',
  '666': 'DATE',
  '667': 'CARDINAL',
  '668': 'CARDINAL',
  '669': 'PERSON',
  '670': 'CARDINAL',
  '671': 'PERSON',
  '672': 'PERSON',
  '673': 'PERSON',
  '674': 'CARDINAL',
  '675': 'PERSON',
  '676': 'PERSON',
  '677': 'CARDINAL',
  '678': 'CARDINAL',
  '679': 'PERSON',
  '680': 'PERSON',
  '681': 'PERSON',
  '682': 'PERSON',
  '683': 'ORDINAL',
  '684': 'PERSON',
  '685': 'PERSON',
  '686': 'PERSON',
  '687': 'PERSON',
  '688': 'PERSON',
  '689': 'CARDINAL',
  '690': 'PERSON',
  '691': 'NORP',
  '692': 'PERSON',
  '693': 'PERSON',
  '694': 'FAC',
  '695': 'PERSON',
  '696': 'PERSON',
  '697': 'PERSON',
  '698': 'PERSON',
  '699': 'PERSON',
  '700': 'PERSON',
  '701': 'PERSON',
  '702': 'PERSON',
  '703': 'ORDINAL',
  '704': 'CARDINAL',
  '705': 'PERSON',
  '706': 'PERSON',
  '707': 'PERSON',
  '708': 'PERSON',
  '709': 'CARDINAL',
  '710': 'PERSON',
  '711': 'CARDINAL',
  '712': 'PERSON',
  '713': 'ORG',
  '714': 'ORG',
  '715': 'LAW',
  '716': 'ORG',
  '717': 'NORP',
  '718': 'DATE',
  '719': 'ORG',
  '720': 'GPE',
  '721': 'LOC',
  '722': 'GPE',
  '723': 'CARDINAL',
  '724': 'DATE',
  '725': 'DATE',
  '726': 'GPE',
  '727': 'ORG',
  '728': 'ORG',
  '729': 'QUANTITY',
  '730': 'ORDINAL',
  '731': 'DATE',
  '732': 'DATE',
  '733': 'CARDINAL',
  '734': 'DATE',
  '735': 'DATE',
  '736': 'CARDINAL',
  '737': 'PERSON',
  '738': 'PERSON',
  '739': 'NORP',
  '740': 'PERSON',
  '741': 'PERSON',
  '742': 'PERSON',
  '743': 'PERSON',
  '744': 'ORDINAL',
  '745': 'CARDINAL',
  '746': 'CARDINAL',
  '747': 'CARDINAL',
  '748': 'GPE',
  '749': 'GPE',
  '750': 'ORG',
  '751': 'CARDINAL',
  '752': 'CARDINAL',
  '753': 'DATE',
  '754': 'DATE',
  '755': 'TIME',
  '756': 'ORDINAL',
  '757': 'CARDINAL',
  '758': 'CARDINAL',
  '759': 'CARDINAL',
  '760': 'ORG',
  '761': 'ORG',
  '762': 'ORDINAL',
  '763': 'CARDINAL',
  '764': 'WORK_OF_ART',
  '765': 'ORG',
  '766': 'PERSON',
  '767': 'CARDINAL',
  '768': 'CARDINAL',
  '769': 'ORDINAL',
  '770': 'CARDINAL',
  '771': 'CARDINAL',
  '772': 'CARDINAL',
  '773': 'CARDINAL',
  '774': 'CARDINAL',
  '775': 'PERSON',
  '776': 'CARDINAL',
  '777': 'PERSON',
  '778': 'DATE',
  '779': 'CARDINAL',
  '780': 'NORP',
  '781': 'PERSON',
  '782': 'GPE',
  '783': 'NORP',
  '784': 'GPE',
  '785': 'NORP',
  '786': 'PERSON',
  '787': 'NORP',
  '788': 'NORP',
  '789': 'CARDINAL',
  '790': 'CARDINAL',
  '791': 'NORP',
  '792': 'CARDINAL',
  '793': 'CARDINAL',
  '794': 'CARDINAL',
  '795': 'DATE',
  '796': 'CARDINAL',
  '797': 'PERSON',
  '798': 'PERSON',
  '799': 'NORP',
  '800': 'CARDINAL',
  '801': 'DATE',
  '802': 'PERSON',
  '803': 'PERSON',
  '804': 'LAW',
  '805': 'PERSON',
  '806': 'GPE',
  '807': 'LOC',
  '808': 'NORP',
  '809': 'GPE',
  '810': 'CARDINAL',
  '811': 'DATE',
  '812': 'ORDINAL',
  '813': 'CARDINAL',
  '814': 'PERSON',
  '815': 'NORP',
  '816': 'PERSON',
  '817': 'PERSON',
  '818': 'ORG',
  '819': 'CARDINAL',
  '820': 'CARDINAL',
  '821': 'PERSON',
  '822': 'GPE',
  '823': 'GPE',
  '824': 'ORG',
  '825': 'PERSON',
  '826': 'CARDINAL',
  '827': 'PERSON',
  '828': 'DATE',
  '829': 'TIME',
  '830': 'TIME',
  '831': 'DATE',
  '832': 'CARDINAL',
  '833': 'CARDINAL',
  '834': 'CARDINAL',
  '835': 'CARDINAL',
  '836': 'LOC',
  '837': 'LOC',
  '838': 'PERSON',
  '839': 'CARDINAL',
  '840': 'LOC',
  '841': 'PERSON',
  '842': 'PERSON',
  '843': 'PERSON',
  '844': 'DATE',
  '845': 'NORP',
  '846': 'LOC',
  '847': 'ORDINAL',
  '848': 'CARDINAL',
  '849': 'PERSON',
  '850': 'DATE',
  '851': 'ORG',
  '852': 'GPE',
  '853': 'GPE',
  '854': 'PERSON',
  '855': 'NORP',
  '856': 'CARDINAL',
  '857': 'CARDINAL',
  '858': 'ORG',
  '859': 'PERSON',
  '860': 'GPE',
  '861': 'PERSON',
  '862': 'DATE',
  '863': 'PERSON',
  '864': 'PERSON',
  '865': 'LOC',
  '866': 'ORG',
  '867': 'PERSON',
  '868': 'DATE',
  '869': 'PERSON',
  '870': 'GPE',
  '871': 'PERSON',
  '872': 'PERSON',
  '873': 'TIME',
  '874': 'PERSON',
  '875': 'CARDINAL',
  '876': 'DATE',
  '877': 'DATE',
  '878': 'CARDINAL',
  '879': 'GPE',
  '880': 'LAW',
  '881': 'PERSON',
  '882': 'PERSON',
  '883': 'LOC',
  '884': 'PERSON',
  '885': 'NORP',
  '886': 'NORP',
  '887': 'CARDINAL',
  '888': 'DATE',
  '889': 'NORP',
  '890': 'ORG',
  '891': 'GPE',
  '892': 'ORG',
  '893': 'ORDINAL',
  '894': 'NORP',
  '895': 'NORP',
  '896': 'DATE',
  '897': 'LOC',
  '898': 'ORG',
  '899': 'WORK_OF_ART',
  '900': 'PERSON',
  '901': 'PERSON',
  '902': 'PERSON',
  '903': 'NORP',
  '904': 'PERSON',
  '905': 'LOC',
  '906': 'PERSON',
  '907': 'CARDINAL',
  '908': 'PERSON',
  '909': 'PERSON',
  '910': 'PERSON',
  '911': 'ORG',
  '912': 'NORP',
  '913': 'GPE',
  '914': 'PERSON',
  '915': 'PERSON',
  '916': 'ORDINAL',
  '917': 'PERSON',
  '918': 'PERSON',
  '919': 'PERSON',
  '920': 'CARDINAL',
  '921': 'ORG',
  '922': 'CARDINAL',
  '923': 'PERSON',
  '924': 'PERSON',
  '925': 'DATE',
  '926': 'PERSON',
  '927': 'PERSON',
  '928': 'ORG',
  '929': 'PERSON',
  '930': 'CARDINAL',
  '931': 'NORP',
  '932': 'GPE',
  '933': 'DATE',
  '934': 'PERSON',
  '935': 'PERSON',
  '936': 'DATE',
  '937': 'GPE',
  '938': 'GPE',
  '939': 'PERSON',
  '940': 'ORDINAL',
  '941': 'NORP',
  '942': 'PERSON',
  '943': 'CARDINAL',
  '944': 'CARDINAL',
  '945': 'CARDINAL',
  '946': 'LAW',
  '947': 'TIME',
  '948': 'PERSON',
  '949': 'LOC',
  '950': 'LOC',
  '951': 'CARDINAL',
  '952': 'CARDINAL',
  '953': 'PERSON',
  '954': 'PERSON',
  '955': 'PERSON',
  '956': 'PERSON',
  '957': 'PERSON',
  '958': 'CARDINAL',
  '959': 'PERSON',
  '960': 'CARDINAL',
  '961': 'PERSON',
  '962': 'ORG',
  '963': 'PERSON',
  '964': 'PERSON',
  '965': 'CARDINAL',
  '966': 'CARDINAL',
  '967': 'NORP',
  '968': 'CARDINAL',
  '969': 'PERSON',
  '970': 'PERSON',
  '971': 'ORG',
  '972': 'PERSON',
  '973': 'PERSON',
  '974': 'PERSON',
  '975': 'PERSON',
  '976': 'PERSON',
  '977': 'ORG',
  '978': 'PERSON',
  '979': 'TIME',
  '980': 'DATE',
  '981': 'PERSON',
  '982': 'DATE',
  '983': 'DATE',
  '984': 'ORG',
  '985': 'TIME',
  '986': 'PERSON',
  '987': 'CARDINAL',
  '988': 'CARDINAL',
  '989': 'DATE',
  '990': 'DATE',
  '991': 'PERSON',
  '992': 'GPE',
  '993': 'CARDINAL',
  '994': 'CARDINAL',
  '995': 'CARDINAL',
  '996': 'CARDINAL',
  '997': 'CARDINAL',
  '998': 'CARDINAL',
  '999': 'TIME',
  ...},
 'value': {'0': 'John H. Watson',
  '1': 'M.D.',
  '2': 'the Army Medical Department',
  '3': 'Chapter I.',
  '4': 'Sherlock Holmes  ',
  '5': 'the year 1878',
  '6': 'the University of London',
  '7': 'Netley',
  '8': 'Fifth',
  '9': 'India',
  '10': 'second',
  '11': 'Afghan',
  '12': 'Bombay',
  '13': 'Berkshires',
  '14': 'Maiwand',
  '15': 'Jezail',
  '16': 'Ghazis',
  '17': 'Murray',
  '18': 'British',
  '19': 'Peshawar',
  '20': 'Indian',
  '21': 'months',
  '22': 'England',
  '23': 'Orontes',
  '24': 'a month later',
  '25': 'Portsmouth',
  '26': 'the next nine months',
  '27': 'England',
  '28': 'eleven shillings',
  '29': 'London',
  '30': 'Empire',
  '31': 'Strand',
  '32': 'the very day',
  '33': 'the Criterion Bar',
  '34': 'Stamford',
  '35': 'Bart',
  '36': 'London',
  '37': 'Stamford',
  '38': 'Holborn',
  '39': 'Watson',
  '40': 'London',
  '41': 'second',
  '42': 'first',
  '43': 'this morning',
  '44': 'Stamford',
  '45': 'Sherlock Holmes',
  '46': 'I.',
  '47': 'first',
  '48': 'Afghanistan',
  '49': 'weeks',
  '50': 'morning to night',
  '51': 'Holborn',
  '52': 'Stamford',
  '53': 'Stamford',
  '54': 'Holmes',
  '55': 'Watson',
  '56': 'Sherlock Holmes',
  '57': 'Stamford',
  '58': 'Afghanistan',
  '59': 'years',
  '60': 'more than one',
  '61': 'Guiacum',
  '62': 'a few hours old',
  '63': 'hundreds',
  '64': 'one',
  '65': 'months',
  '66': 'Von Bischoff',
  '67': 'Frankfort',
  '68': 'last year',
  '69': 'Mason of Bradford',
  '70': 'Muller',
  '71': 'Lefevre',
  '72': 'Montpellier',
  '73': 'Samson',
  '74': 'Orleans',
  '75': 'Stamford',
  '76': 'Sherlock Holmes',
  '77': 'Stamford',
  '78': 'a high three',
  '79': 'Baker Street',
  '80': 'days',

In [47]:
pd.DataFrame(response3.json()).head()

  category                        value
0   PERSON               John H. Watson
1      GPE                         M.D.
2      ORG  the Army Medical Department
3      LAW                   Chapter I.
4   PERSON            Sherlock Holmes

## Task Endpoint (bonus)

Jika dilihat dari hasil kembalian endpoint sebelumnya nilai return JSON yang dihasilkan sedikit tidak lazim, dimana sewajarnya nilai setiap entitas dikelompokkan sebagai values kedalam setiap kategori. 


**Bonus Task** : Buatlah endpoint `'/get_entities_normalized'` yang menghasilkan JSON dengan key jenis kategori entitas, dan value berupa list dari entitas dengan kategori yang bersangkutan. Berikut ilustrasi dari nilai return endpoint yang diinginkan :  

```python
{category1 : [value1, value2, ... , valuen],
 category2 : [value1, value2, ... , valuen],}
```

# Deployment ke remote host

## Upload code ke git repository (github)

1. Membuat repositori baru 
2. Mengupload file ke repositori baru dan commit changes

## Create Heroku App

1. Membuat aplikasi baru
2. Menyambungkan repositori github kedalam aplikasi baru 
3. Melakukan deployment